### ISSUE TITLE
OS module import fails 

### ISSUE THREAD

**Issue by Wh1teStr1pe** [Tinche/aiofiles#130]
![image](https://user-images.githubusercontent.com/66954477/153713686-f4686c4b-8ebd-440d-9aeb-dbfd90cbb66b.png)

Cannot import correctly anything from ```os.path``` module and cannot use its functions like ```path.exists()```

**Comment by Tinche** [comment]
Ah, you're saying `from aiofiles.os.path import exists` doesn't work?

**Comment by Wh1teStr1pe** [comment]
@Tinche yes, I could fix it only by running ```pip install types-aiofiles```

**Comment by realsuayip** [comment]
I had the same issue today. Installing types-aiofiles wouldn't help me though. Python 3.10.1

**Comment by cpvandehey** [comment]
Same thing. Seeing this in mypy:
`error: Module has no attribute "os"  [attr-defined]`

**Comment by ehn-pkalinowski** [comment]
you need to 
`import aiofiles.os`
I had to look into the sources to deduce it...

**Comment by xhy2008** [comment]
>>> import aiofiles.os
Traceback (most recent call last):                File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/home/aiofiles-23.2.1/src/aiofiles/os.py", line 41, in <module>                                                  link = wrap(os.link)
                ^^^^^^^                         AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?

I got this error.
I tried to change a version,but it didn't work.

**Comment by n-ce** [comment]
> > > > import aiofiles.os
> > > > Traceback (most recent call last):                File "", line 1, in 
> > > > File "/data/data/com.termux/files/home/aiofiles-23.2.1/src/aiofiles/os.py", line 41, in                                                   link = wrap(os.link)
> > > > ^^^^^^^                         AttributeError: module 'os' has no attribute 'link'. Did you mean: 'unlink'?
> 
> I got this error. I tried to change a version,but it didn't work.

Getting the same error.

**Comment by Wh1teStr1pe** [comment]
try this
`from aiofiles import os as aos`

**Comment by n-ce** [comment]
> @xhy2008 @n-ce
> 
> try this `from aiofiles import os as aos`

I tried to remove the `link = wrap(os.link)` line from `os.py` yesterday and it worked. I also learned that this is a fixed issue but not released yet.
