### ISSUE TITLE
ModuleNotFoundError: No module named 'aiofiles.threadpool'

### ISSUE THREAD

**Issue by flatsiedatsie** [Tinche/aiofiles#155]
I'm seeing this error and I'm not sure what's causing it:

```
Traceback (most recent call last):
  File "/home/pi/.webthings/addons/voco/main.py", line 15, in <module>
    from pkg.voco_adapter import VocoAdapter  # noqa
  File "/home/pi/.webthings/addons/voco/pkg/voco_adapter.py", line 26, in <module>
    import aiofiles
  File "/home/pi/.webthings/addons/voco/lib/aiofiles/__init__.py", line 2, in <module>
    from .threadpool import open
ModuleNotFoundError: No module named 'aiofiles.threadpool'
```

**Comment by flatsiedatsie** [comment]
It seems that for some reason the library didn't install properly. The aiofiles library only contained:

```
__init__.py  
__pycache__
```

I fixed it by using  `--upgrade` with the pip install command.
