### ISSUE TITLE
Regression with aiofiles 24.1.0

### ISSUE THREAD

**Issue by riadhelloumi** [Tinche/aiofiles#190]
Hi,

I found a regression with aiofiles 24.1.0. I am using it with asynctempfile and Python 3.10, and when I execute this code:

```
import asynctempfile
async def func():
    async with asynctempfile.NamedTemporaryFile('rb+') as tmp_file:
        print(tmp_file.name)

import asyncio
loop = asyncio.get_event_loop()
loop.run_until_complete(func())
```
I have the output:
```
Traceback (most recent call last):
  File "/home/relloumi/tmp/test.py", line 8, in <module>
    loop.run_until_complete(func())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/relloumi/tmp/test.py", line 3, in func
    async with asynctempfile.NamedTemporaryFile('rb+') as tmp_file:
  File "/home/relloumi/dev/stream_indexer/venv/lib/python3.10/site-packages/aiofiles/base.py", line 63, in __aenter__
    return await self
  File "/home/relloumi/dev/stream_indexer/venv/lib/python3.10/site-packages/aiofiles/base.py", line 59, in __await__
    self._obj = yield from self._coro.__await__()
AttributeError: 'generator' object has no attribute '__await__'. Did you mean: '__init__'?
```
With aiofiles 23.2.1, I have this output:
```
/tmp/tmp5eokcwsx
```
Best regards,
Riadh

**Comment by mjpieters** [comment]
As the [`asynctempfile` project](https://github.com/alemigo/asynctempfile) states:

> This code has been incorporated into the aiofiles depedency and will no longer be maintained here.

Replace `asynctempfile` with `aiofiles.tempfile`:

```
import aiofiles.tempfile as asyncntempfile
async def func():
    async with asynctempfile.NamedTemporaryFile('rb+') as tmp_file:
        print(tmp_file.name)
```

**Comment by Tinche** [comment]
Thanks @mjpieters !

Will close this.

**Comment by riadhelloumi** [comment]
Thank you!
