### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Rouzip** [Tinche/aiofiles#30]
when I import aiofile,it will raise a OS Error like that:
```python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import aiofile
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rouzip/.local/lib/python3.5/site-packages/aiofile/__init__.py", line 1, in <module>
    from .utils import Reader, Writer
  File "/home/rouzip/.local/lib/python3.5/site-packages/aiofile/utils.py", line 3, in <module>
    from .aio import AIOFile
  File "/home/rouzip/.local/lib/python3.5/site-packages/aiofile/aio.py", line 6, in <module>
    from .posix_aio import IO_NOP, IO_WRITE, IO_READ, AIOOperation
  File "aiofile/posix_aio.pyx", line 67, in init aiofile.posix_aio (aiofile/posix_aio.c:7366)
OSError: [Errno 22] Invalid argument
```
I don't know what should I do to fix this problem,can anybody help me?

**Comment by yeraydiazdiaz** [comment]
You're importing a different package [`aiofile`](https://pypi.python.org/pypi/aiofile/) (as opposed to "aiofile**s**") which is a different project you can find help for it at https://github.com/mosquito/aiofile

**Comment by Rouzip** [comment]
Oh,I was stupid...Thanks a lot! @yeraydiazdiaz
